language: python
python:
    - "2.7"

install: pip install -r requirements.txt
env:
  global:
      secure: <grbkb=j8=0#819djx%n6jtupf$0mtej(ps&)d$sz-($2@!84@l>

script:
    - export SECRET_KEY=$SECRET_KEY
    - python manage.py test